apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    field.cattle.io/creatorId: user-mfrws
  creationTimestamp: "2021-11-24T17:48:43Z"
  generation: 3
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-db-agent
  name: db-agent
  namespace: default
  resourceVersion: "368363656"
  selfLink: /apis/apps/v1/namespaces/default/deployments/db-agent
  uid: d91a57cf-bb35-4abf-b46e-91eb33826377
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-db-agent
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-11-24T17:48:43Z"
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-db-agent
    spec:
      containers:
        - image: xianleeti/db-agent:0.09-root
          imagePullPolicy: Always
          name: db-agent
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2021-11-24T17:49:16Z"
      lastUpdateTime: "2021-11-24T17:49:16Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-11-24T17:48:43Z"
      lastUpdateTime: "2023-05-24T10:54:15Z"
      message: ReplicaSet "db-agent-9d8f46485" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: "['deployment:default:db-agent']"
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: "2021-11-24T17:48:43Z"
  labels:
    cattle.io/creator: norman
  name: db-agent
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1beta2
      controller: true
      kind: deployment
      name: db-agent
      uid: d91a57cf-bb35-4abf-b46e-91eb33826377
  resourceVersion: "57783115"
  selfLink: /api/v1/namespaces/default/services/db-agent
  uid: 12c22744-0176-4ea4-be31-b44930d8b89c
spec:
  clusterIP: None
  ports:
    - name: default
      port: 42
      protocol: TCP
      targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-db-agent
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
